### ISSUE TITLE
Problem with JWcsMap.wcs2pix

### ISSUE THREAD

**Issue by talonsoalbi** [malapert/JWcs#88]
Hello!

I think there is a bug in AbstractJWcs:331 when setting the cdInverse matrix. The line 
        setCdInverse(inverse(getCd()));
should be replaced by something like
        setCdInverse(inverse(getCd()).transpose());

As a test I show below a simple code to do some pix2wcs and wcs2pix transformations. With the latest git code the output from the test is:

feb 23, 2022 12:36:26 PM io.github.malapert.jwcs.AbstractJWcs createStandardProjection
INFORMACIÓN: Creates a TAN projection with (crval1,crval2)=(239,951,34,997)
*** ERROR *** PIXEL DISTANCE = 9.087176956375192
*** ERROR *** PIXEL DISTANCE = 16.392334399709416
*** ERROR *** PIXEL DISTANCE = 11.680361651978888
*** ERROR *** PIXEL DISTANCE = 15.912085942824916
*** ERROR *** PIXEL DISTANCE = 8.559224420477559
FOUND 5 ERRORS

After the proposed fix the output is:

feb 23, 2022 12:27:35 PM io.github.malapert.jwcs.AbstractJWcs createStandardProjection
INFORMACIÓN: Creates a TAN projection with (crval1,crval2)=(239,951,34,997)
PIXEL DISTANCE = 1.1476927896008348E-6
PIXEL DISTANCE = 2.563357969749597E-7
PIXEL DISTANCE = 1.905591355810292E-7
PIXEL DISTANCE = 1.0561041208160164E-9
PIXEL DISTANCE = 6.128300236688748E-7
FOUND 0 ERRORS

Compared to other libraries there is still a noticeable difference (around a factor 10), something is still not perfect, but at least the pixel distance is little enough. The testing code is:

    public static void main(String args[]) throws Exception {
        String proj = "TAN";
        int w = 2646, h = 880;
        
        String[] header = new String[] {
            "SIMPLE", "T",
            "BITPIX", "-32",
            "NAXIS", "2",
            "NAXIS1", ""+w,
            "NAXIS2", ""+h,
            "EXTEND", "T",
            "CRVAL1", "239.9510602335937",
            "CRVAL2", "34.99748174786235",
            "CRPIX1", "0.0",
            "CRPIX2", "0.0",
            "CD1_1", "0.0000262579524",
            "CD2_1", "-0.00000943433315",
            "CD1_2", "-0.00000933583267",
            "CD2_2", "-0.0000263566406",
            "EPOCH", "2000.0",
            "EQUINOX", "2000.0",
            "DATE-OBS", "2000.0",
            "CTYPE1", "RA---" + proj,
            "CTYPE2", "DEC--" + proj,
            "RADECSYS", "FK5",
            "END", "null"
        };
        final Map<String, String> keyMap = new HashMap<>();
        Header hdr = new Header();
        for (int i=0; i<header.length;i=i+2) {
            double v = -1;
            boolean isNumber = false;
            try {
                v = Double.parseDouble(header[i+1]);
                if (header[i+1].indexOf(".") >=0) isNumber = true;
            } catch (Exception exc) {}
            if (isNumber) {
                hdr.addValue(header[i], v, null);
            } else {
                hdr.addValue(header[i], header[i+1], null);
            }
            keyMap.put(header[i], header[i+1]);
        }
        final JWcsMap wcsJWcs = new JWcsMap(keyMap);
        wcsJWcs.doInit();

        int n = 5;
        int nErr = 0;
        for (int i=0;i<n;i++) {
            double px = (Math.random() * w * 3) - w;
            double py = (Math.random() * h * 3) - h;
            Point2D.Double p = new Point2D.Double(px, py);
            double[] sky = wcsJWcs.pix2wcs(px, py);
            
            double[] pixBack = wcsJWcs.wcs2pix(sky[0], sky[1]);
            Point2D.Double pBack = new Point2D.Double(pixBack[0], pixBack[1]);

            double d = p.distance(pBack);
            if (d > 0.001) {
                System.err.println("*** ERROR *** PIXEL DISTANCE = " + d);
                nErr ++;
            } else {
                System.out.println("PIXEL DISTANCE = " + d);                
            }
        }

        System.out.println("FOUND "+nErr+" ERRORS");
    }

**Comment by malapert** [comment]
Hi, 

Thanks a lot for the bug report. Unfortunately, the project is abandoned. So it is not maintain anymore

Regards
